### ISSUE TITLE
IOWebSocketChannel loses the first message if they come from the server more than one when connecting

### ISSUE THREAD

**Issue by Claus1** [dart-lang/web_socket_channel#80] opened 2019-09-22 06:45 UTC
Python server which sends back 2 messages to the client:
 
```
class GuiServer(WebSocket):
   def handleConnected(self):
       self.sendMessage(jsonString(data1))
       self.sendMessage(jsonString(data2))
 
```
My Python websocket client gets this messages ok, but IOWebSocketChannel loses first message and gets only the second when connecting.
If the server sends only 1 message IOWebSocketChannel gets it ok. Not 2. The flutter code:
 
```
void createServerChannel() {
 if (serverAddress != null)
   serverChannel = IOWebSocketChannel.connect(serverAddress);
}
....
....
             StreamBuilder(
                 stream: serverChannel.stream,
                 builder: (context, snapshot) {
                   if (snapshot.data != null)
                   {
                     var data = json.decode(snapshot.data); 


```

**Comment by changhc** [comment] 2020-04-11 08:23
I had the same issue as yours and I looked into the libraries involved. The problem is not in `IOWebSocketChannel` but in `StreamBuilder`. If you read the source code [here](https://github.com/flutter/flutter/blob/f139b11009/packages/flutter/lib/src/widgets/async.dart#L409), you can see that `StreamBuilder` doesn't handle accumulate any data. It treats every incoming record as an individual pack of messages and stores the latest one into its state, so if you miss out any snapshot, you lose it for good. On the other hand, according to the [doc](https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html),

> The actual sequence of invocations of the builder depends on the relative timing of events produced by the stream and the build rate of the Flutter pipeline.

Therefore, it seems that there's no guarantee that the builder will be triggered on every incoming message. I guess it's possible that if two new messages come in when the builder is running, the first one won't be processed since it will simply be overwritten by the second one.

My solution was to create a new class that extends `StreamBuilderBase` and preserve my data in the `afterData` method. In this case, we need to handle when to clean up the buffer ourselves.

**Comment by Claus1** [comment] 2020-04-12 16:52
@changhc I think better to fix the bug)

**Comment by changhc** [comment] 2020-04-13 02:28
I think it's more like a matter of design rather than a bug, though I don't get their logic in designing the `StreamBuilder` this way. I'll try to talk to the authors.

**Comment by natebosch** [comment] 2020-04-13 21:47
Closing since this appears to be confusion about `StreamBuilder` unrelated to this repository.

Note that you can use something like [`tap`](https://pub.dev/documentation/stream_transform/latest/stream_transform/Tap/tap.html) to "see" the values on a stream and do something else with them. (or use `map` if you don't want the extra dependency on `stream_transform`).

```dart
             StreamBuilder(
                 stream: serverChannel.stream.tap((value) {
                   print('Got value :$value');
                 }),
                 builder: (context, snapshot) {
                   if (snapshot.data != null) {
                     var data = json.decode(snapshot.data);

**Closed by natebosch** 2020-04-13 21:47 UTC
